### ISSUE TITLE
Feature request: Allow `try_only` to define specific taxa to test in `differentialTest()`

### ISSUE THREAD

**Issue by mikemc** [bryandmartin/corncob#85]
A small feature request...I'd like to be able to do something like
```r
focal_taxa <- filter_taxa(soil, function(x) mean(x) > 0.1) # Gives a logical vector

da_analysis <- differentialTest(formula = ~ DayAmdmt,
  phi.formula = ~ DayAmdmt,
  formula_null = ~ 1,
  phi.formula_null = ~ DayAmdmt,
  test = "Wald", boot = FALSE,
  data = soil,
  try_only = focal_taxa
)
```
or the same thing, but where `focal_taxa` is a vector of taxa names, rather than a logical vector.

Motivation: I usually only want to test a subset of taxa in order to maximize power, even after I have filtered out very low abundance/prevalence taxa. I don't want to simply filter to the taxa I want to test, because that would change the proportions of the focal taxa. As designed, the `try_only` argument lets you test just, e.g. the first 100 taxa, so reordering taxa in a phyloseq object so that the desired taxa are first is a possible solution, but is somewhat undesirable because taxa ordering in phyloseq objects is undocumented and is fixed by the phylogenetic tree when it exists. So it would be very handy to be able to generate a list of taxa to test, and then supply this list to `differentialTest()`.

If this seems like a worthwhile feature but is too low-priority I can try my hand at implementing it once I find some time to look through the code.

**Comment by bryandmartin** [comment]
This is easy! I'm updating another feature request for differentialTest soon and will add this at the same time. Thanks for the suggestion.

**Comment by bryandmartin** [comment]
Hi @mikemc , thanks for posting this issue and for your patience on this. I'm just now creating a pull request to add this feature. Let me know if you have any issues with it!

**Comment by bryandmartin** [comment]
Fixed in 7e25fe4

**Comment by mikemc** [comment]
Hi @bryandmartin, this still isn't working for me:

    library(corncob)
    library(magrittr)

    data(soil_phylo)
    soil <- soil_phylo %>%
    phyloseq::subset_samples(DayAmdmt %in% c(11,21)) %>%
    phyloseq::tax_glom("Phylum")
    taxa <- phyloseq::taxa_names(soil)[1:5]
    print(taxa)
    #> [1] "OTU.19"  "OTU.1"   "OTU.15"  "OTU.3"   "OTU.133"
    da_analysis <- differentialTest(formula = ~ DayAmdmt,
                                    phi.formula = ~ DayAmdmt,
                                    formula_null = ~ 1,
                                    phi.formula_null = ~ DayAmdmt,
                                    test = "Wald", boot = FALSE,
                                    data = soil,
                                    fdr_cutoff = 0.05,
                                    try_only = taxa)
    #> Error in validObject(.Object): invalid class "otu_table" object: 
    #>  OTU abundance data must have non-zero dimensions.

<sup>Created on 2020-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikemc** [comment]
Ah I see, `try_only` has to be the indexes of the taxa, not the names. I didn't realize that from the documentation - perhaps worth adding a clarification

**Comment by bryandmartin** [comment]
Re-opening this! Yes, for now it has to be indexes of the taxa, but I'll keep this open until I modify it to include the names. That seems very sensible!

Thanks Mike!

**Comment by jessjarett** [comment]
Hi @bryandmartin, is it possible to add this same feature to contrastsTest?

**Comment by bryandmartin** [comment]
@jessjarett @mikemc 

Thanks for your patience, I finally got around to doing this as I prepare corncob for CRAN submission!
